import { Toaster } from '@/components/ui/toaster';
import { Header, SideBar } from '@/features';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen max-w-[100vw] overflow-x-hidden flex p-5 bg-neutral-950`}
      >
        <SideBar />
        <main className="w-full max-h-[100vh] overflow-auto">
          <Header />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
